-- VHDL module instantiation generated by SCUBA Diamond_2.2_Production (99)
-- Module  Version: 4.9
-- Thu Oct 03 15:08:06 2013

-- parameterized module component declaration
library IEEE;
use IEEE.std_logic_1164.all;

library ECP3;
use ECP3.components.all;
component AERFiFo_TN
    port (Data: in  std_logic_vector(17 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        Q: out  std_logic_vector(17 downto 0); Empty: out  std_logic; 
        Full: out  std_logic; AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : AERFiFo_TN
    port map (Data(17 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, 
        Reset=>__, Q(17 downto 0)=>__, Empty=>__, Full=>__, AlmostEmpty=>__, 
        AlmostFull=>__);
