#ifndef _INCLUDED_EXAMPLE_CONFIG_H_
#define _INCLUDED_EXAMPLE_CONFIG_H_ 1

// Feature configuration
#define STRING_PRODUCT 'F', 0x00, 'X', 0x00, '3', 0x00, ' ', 0x00, 'E', 0x00, 'X', 0x00, 'A', 0x00, 'M', 0x00, 'P', 0x00, 'L', 0x00, 'E', 0x00
#define STRING_PRODUCT_LEN 22

#define GPIF_32BIT_SUPPORT_ENABLED (0)
#define I2C_SUPPORT_ENABLED (0)
#define SPI_SUPPORT_ENABLED (1)
#define GPIO_SUPPORT_ENABLED (1)

#define DEVICE_SPECIFIC_INITIALIZATION (1)
#define DEVICE_SPECIFIC_VENDOR_REQUESTS (1)

#define DMA_USBTOFIFO_CALLBACK (0)
#define DMA_FIFOTOUSB_CALLBACK (0)

#endif /* _INCLUDED_EXAMPLE_CONFIG_H_ */
