@TM:1399999643
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[15] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[14] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[13] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[12] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[11] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[10] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[9] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[8] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[7] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[6] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[5] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[4] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[3] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[2] to be optimized by the mapper. 
@W: FX469 :"":0:0:0:-1|Found undriven nets DebugxSIO[1] to be optimized by the mapper. 
@W: FX474 :"":0:0:0:-1|User-specified initial value defined for some sequential elements which can prevent optimum synthesis results from being achieved. 
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF666 :"":0:0:0:-1|Clock conversion enabled 
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":91:57:91:61|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":91:57:91:61|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":177:2:177:5|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":177:2:177:5|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":177:2:177:5|M
@W: MT531 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":177:2:177:5|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":267:2:267:5|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":753:7:753:30|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":794:2:794:3|M
@W: MT462 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\imustatemachine.vhd":794:2:794:3|M
@W: MT529 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\shiftregister.vhd":52:4:52:5|M
@W: MT529 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\shiftregister.vhd":65:4:65:5|M
@W: MT529 :"c:\users\haza\documents\jaer\devicefirmwarepcblayout\latticemachxo\sbret10_2_imu\sourcecode\wordregister.vhd":63:4:63:5|M
