/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_pseye_PSEyeCamera */

#ifndef _Included_uk_ac_imperial_pseye_PSEyeCamera
#define _Included_uk_ac_imperial_pseye_PSEyeCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeGetCameraCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeGetCameraCount
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeGetCameraUUID
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeGetCameraUUID
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCreateCamera
 * Signature: (IIIF)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCreateCamera
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeDestroyCamera
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeDestroyCamera
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCameraStart
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCameraStart
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCameraStop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCameraStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCameraLED
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCameraLED
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeSetCameraParameter
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeSetCameraParameter
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeGetCameraParameter
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeGetCameraParameter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCameraGetFrameDimensions
 * Signature: (I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCameraGetFrameDimensions
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     uk_ac_imperial_pseye_PSEyeCamera
 * Method:    PSEyeCameraGetFrame
 * Signature: (ILjava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_imperial_pseye_PSEyeCamera_PSEyeCameraGetFrame
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
