/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest */

#ifndef _Included_ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest
#define _Included_ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest
 * Method:    runNative
 * Signature: (IIILch/unizh/ini/jaer/projects/apsdvsfusion/NativeConvolutionTest;)V
 */
JNIEXPORT void JNICALL Java_ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest_runNative
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest
 * Method:    initNativeSimpleClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest_initNativeSimpleClass
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest
 * Method:    destroyNativeSimpleClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_unizh_ini_jaer_projects_apsdvsfusion_NativeConvolutionTest_destroyNativeSimpleClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
