
package uk.ac.imperial.pseye.dvs;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import javax.swing.JPanel;

/*
 * JPanel used to control PSEye settings.
 * Interacts through the PSEyeDriverInterface so can use a PSEyechip or camera 
 * itself. 
 * 
 * @author mlk
 */
public class PSEyeDVSPanel extends JPanel implements Observer {

    private final static Logger log = Logger.getLogger("PSEyeDVSPanel");
    public PSEyeModelDVS chip;
    protected boolean refresh = false;

    /* Create a control panel 
     * 
     * @param driver: the interface to observer and use to control the camera
     */
    public PSEyeDVSPanel(PSEyeModelDVS chip) {
        this.chip = chip;
        // create all panel components
        initComponents();
        
        // read current driver settings
        setComponents();
        
        // add this to the driver Observable
        chip.addObserver(this);
    }
    
    /*
    private void setFileModified() {
        if (driver != null && driver.getAeViewer() != null && driver.getAeViewer().getBiasgenFrame() != null) {
            driver.getAeViewer().getBiasgenFrame().setFileModified(true);
        }
    }
     */
    
    /* Read the driver settings and set components to these values 
     * 
     */
    synchronized private void setComponents() {
        refresh = true;
        
        itCB.setSelected(chip.getLinearInterpolateTimeStamp());
        gcCB.setSelected(chip.getIsGamma());
        lcCB.setSelected(chip.getIsLensCorrection());
        
        bgSp.setModel(new SpinnerNumberModel(chip.getBackgroundEventRatePerPixelHz(), 
                0, 1000.0, 1));
        
        llCB.setSelected(chip.getIsLogValue());
        
        ltSp.setModel(new SpinnerNumberModel(chip.getLogTransitionValue(), 
                0, 255, 1));
        
        expSp.setModel(new SpinnerNumberModel(chip.getExpWeight(), 
                0, 10, 1));
        
        onSl.setMinimum(1);
        onSl.setMaximum(255);
        onSl.setValue((int) Math.ceil(chip.getSigmaOnThreshold()));
        onSp.setModel(new SpinnerNumberModel(chip.getSigmaOnThreshold(),
                1., 255., 1.));
        
        onstdSp.setModel(new SpinnerNumberModel(chip.getSigmaOnDeviation() * 100, 
                0., 100., 1.));
                        
        offSl.setMinimum(1);
        offSl.setMaximum(255);
        offSl.setValue((int) Math.ceil(chip.getSigmaOffThreshold()));
        offSp.setModel(new SpinnerNumberModel(chip.getSigmaOffThreshold(),
                1., 255., 1.));     
        
        offstdSp.setModel(new SpinnerNumberModel(chip.getSigmaOffDeviation() * 100, 
                0., 100., 1.));
                
        revalidate();
        refresh = false;
    }

   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        onSl = new javax.swing.JSlider();
        offSl = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        offSp = new javax.swing.JSpinner();
        onSp = new javax.swing.JSpinner();
        onstdSp = new javax.swing.JSpinner();
        offstdSp = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gcCB = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lcCB = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        itCB = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        bgSp = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        ltSp = new javax.swing.JSpinner();
        expSp = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        llCB = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Model"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        setMinimumSize(new java.awt.Dimension(300, 435));
        setPreferredSize(new java.awt.Dimension(300, 435));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thresholds"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        onSl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onSlStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(onSl, gridBagConstraints);

        offSl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offSlStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(offSl, gridBagConstraints);

        jLabel7.setText("ON std (%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("OFF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel8, gridBagConstraints);

        offSp.setToolTipText("CL eye exposure value (0-511)");
        offSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(offSp, gridBagConstraints);

        onSp.setToolTipText("CL eye exposure value (0-511)");
        onSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(onSp, gridBagConstraints);

        onstdSp.setToolTipText("CL eye exposure value (0-511)");
        onstdSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onstdSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(onstdSp, gridBagConstraints);

        offstdSp.setToolTipText("CL eye exposure value (0-511)");
        offstdSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offstdSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(offstdSp, gridBagConstraints);

        jLabel9.setText("ON");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel14.setText("OFF std (%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel14, gridBagConstraints);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Transforms"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        gcCB.setToolTipText("");
        gcCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(gcCB, gridBagConstraints);

        jLabel15.setText("Gamma Correction");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel15, gridBagConstraints);

        jLabel16.setText("Lens Correction");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel16, gridBagConstraints);

        lcCB.setToolTipText("");
        lcCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(lcCB, gridBagConstraints);

        jLabel18.setText("Interpolate Timestamps");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel18, gridBagConstraints);

        itCB.setToolTipText("");
        itCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(itCB, gridBagConstraints);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Noise"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Background Rate (Hz)");
        jLabel19.setAlignmentY(0.0F);
        jLabel19.setMaximumSize(null);
        jLabel19.setMinimumSize(null);
        jLabel19.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel19, gridBagConstraints);

        bgSp.setToolTipText("Rate of RED events due to reset leakage");
        bgSp.setMaximumSize(null);
        bgSp.setMinimumSize(null);
        bgSp.setPreferredSize(null);
        bgSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel3.add(bgSp, gridBagConstraints);

        add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Log-Linear Settings"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        ltSp.setToolTipText("Value at which to use log transform");
        ltSp.setMaximumSize(null);
        ltSp.setMinimumSize(null);
        ltSp.setPreferredSize(null);
        ltSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ltSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel5.add(ltSp, gridBagConstraints);

        expSp.setToolTipText("Exponential weighting to pre-log to further reduce noise");
        expSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                expSpStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel5.add(expSp, gridBagConstraints);

        jLabel20.setText("Enable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Exp Weighting");
        jLabel21.setMaximumSize(null);
        jLabel21.setMinimumSize(null);
        jLabel21.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jLabel21, gridBagConstraints);

        llCB.setToolTipText("");
        llCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel5.add(llCB, gridBagConstraints);

        jLabel22.setText("Threshold");
        jLabel22.setMaximumSize(null);
        jLabel22.setMinimumSize(null);
        jLabel22.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(jLabel22, gridBagConstraints);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void bgSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgSpStateChanged
        if (!refresh) 
            chip.setBackgroundEventRatePerPixelHz((Double) bgSp.getValue());
    }//GEN-LAST:event_bgSpStateChanged

    private void onSlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onSlStateChanged
        if (!refresh) 
            chip.setSigmaOnThreshold(onSl.getValue());
    }//GEN-LAST:event_onSlStateChanged

    private void offSlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offSlStateChanged
        if (!refresh)
            chip.setSigmaOffThreshold(offSl.getValue());
    }//GEN-LAST:event_offSlStateChanged

    private void offSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offSpStateChanged
        if (!refresh)
            chip.setSigmaOffThreshold((Double) offSp.getValue());
    }//GEN-LAST:event_offSpStateChanged

    private void onSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onSpStateChanged
        if (!refresh)
            chip.setSigmaOnThreshold((Double) onSp.getValue());
    }//GEN-LAST:event_onSpStateChanged

    private void onstdSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onstdSpStateChanged
        if (!refresh)
            chip.setSigmaOnDeviation((Double) onstdSp.getValue() / 100.0);
    }//GEN-LAST:event_onstdSpStateChanged

    private void offstdSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offstdSpStateChanged
        if (!refresh)
            chip.setSigmaOffDeviation((Double) offstdSp.getValue() / 100.0);
    }//GEN-LAST:event_offstdSpStateChanged

    private void gcCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcCBActionPerformed
        if (!refresh)
            chip.setIsGamma(gcCB.isSelected());
    }//GEN-LAST:event_gcCBActionPerformed

    private void lcCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcCBActionPerformed
    if (!refresh)
            chip.setIsLensCorrection(lcCB.isSelected());
    }//GEN-LAST:event_lcCBActionPerformed

    private void ltSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ltSpStateChanged
        if (!refresh) 
            chip.setLogTransitionValue((Double) ltSp.getValue());
    }//GEN-LAST:event_ltSpStateChanged

    private void itCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCBActionPerformed
    if (!refresh)
            chip.setLinearInterpolateTimeStamp(itCB.isSelected());
    }//GEN-LAST:event_itCBActionPerformed

    private void expSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_expSpStateChanged
        if (!refresh) 
            chip.setExpWeight((Double) expSp.getValue());
    }//GEN-LAST:event_expSpStateChanged

    private void llCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llCBActionPerformed
        if (!refresh)
            chip.setIsLogValue(llCB.isSelected());
    }//GEN-LAST:event_llCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bgSp;
    private javax.swing.JSpinner expSp;
    private javax.swing.JCheckBox gcCB;
    private javax.swing.JCheckBox itCB;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox lcCB;
    private javax.swing.JCheckBox llCB;
    private javax.swing.JSpinner ltSp;
    private javax.swing.JSlider offSl;
    private javax.swing.JSpinner offSp;
    private javax.swing.JSpinner offstdSp;
    private javax.swing.JSlider onSl;
    private javax.swing.JSpinner onSp;
    private javax.swing.JSpinner onstdSp;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the driver
     */
    public PSEyeModelDVS getChip() {
        return chip;
    }

    /**
     * @param driver the driver to set
     */
    public void setChip(PSEyeModelDVS chip) {
        this.chip = chip;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (o != null && o == chip && arg instanceof PSEyeModelDVS.EVENT_MODEL) {
            // update all components and models just in case
            setComponents();
        }
    }
}
