-- VHDL netlist generated by SCUBA Diamond_1.0_Production (529)
-- Module  Version: 5.4
--C:\LatticeDiamond\diamond\1.0\ispfpga\bin\nt\scuba.exe -w -n AERfifo -lang vhdl -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 1024 -width 16 -rwidth 16 -no_enable -pe 10 -pf 252 -e 

-- Tue Nov 16 17:05:21 2010

library IEEE;
use IEEE.std_logic_1164.all;

entity AERfifo is
    port (
        Data: in  std_logic_vector(15 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(15 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end AERfifo;

architecture Structure of AERfifo is
    -- internal signal declarations
    signal Empty_int: std_logic;
    signal Full_int: std_logic;
	
	component pmi_fifo_dc is
     generic (
       pmi_data_width_w : integer := 18; 
       pmi_data_width_r : integer := 18; 
       pmi_data_depth_w : integer := 256; 
       pmi_data_depth_r : integer := 256; 
       pmi_full_flag : integer := 256; 
       pmi_empty_flag : integer := 0; 
       pmi_almost_full_flag : integer := 252; 
       pmi_almost_empty_flag : integer := 4; 
       pmi_regmode : string := "reg"; 
       pmi_resetmode : string := "async"; 
       pmi_family : string := "EC" ; 
       module_type : string := "pmi_fifo_dc"; 
       pmi_implementation : string := "EBR"
 
    );
    port (
     Data : in std_logic_vector(pmi_data_width_w-1 downto 0);
     WrClock: in std_logic;
     RdClock: in std_logic;
     WrEn: in std_logic;
     RdEn: in std_logic;
     Reset: in std_logic;
     RPReset: in std_logic;
     Q : out std_logic_vector(pmi_data_width_r-1 downto 0);
     Empty: out std_logic;
     Full: out std_logic;
     AlmostEmpty: out std_logic;
     AlmostFull: out std_logic
   );
  end component pmi_fifo_dc;
begin
    -- component instantiation statements
	AERfifo_0_1: pmi_fifo_dc
    generic map (
       pmi_data_width_w => 16,
       pmi_data_depth_w => 8,
	   pmi_data_width_r => 16,
       pmi_data_depth_r => 8,
       pmi_full_flag => 8,
       pmi_empty_flag => 0,
       pmi_almost_full_flag => 6,
       pmi_almost_empty_flag => 2,
       pmi_regmode => "noreg",
	   pmi_resetmode => "async",
       pmi_family => "ECP3",
       pmi_implementation => "LUT"
    )
    port map (
     Data => Data,
     WrClock => WrClock,
	 RdClock => RdClock,
     WrEn => WrEn,
     RdEn => RdEn,
     Reset => Reset,
	 RPReset => RPReset,
     Q => Q,
     Empty => Empty_int,
     Full => Full_int,
     AlmostEmpty => AlmostEmpty,
     AlmostFull => AlmostFull
   );
 
    Empty <= Empty_int;
    Full <= Full_int;
end Structure;
