-- VHDL module instantiation generated by SCUBA Diamond_2.0_Production (151)
-- Module  Version: 5.3
-- Sat Dec 22 15:29:20 2012

-- parameterized module component declaration
component DigLogClock
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : DigLogClock
    port map (CLK=>__, RESET=>__, CLKOP=>__, LOCK=>__);
