
package uk.ac.imperial.vsbe;

import javax.swing.JPanel;

/**
 * A panel for controlling a PSEyeModelChip and PSEyeCamera
 * This is added to the content panel of BiasgenFrame. 
 * It encapsulates the PSEyeSettingPanel, CameraFramePanel, and PSEyeModelPanel
 *
 * @author  mlk
 */
public class CameraChipBiasgenPanel extends JPanel {
    public CameraChipBiasgen<?> biasgen;
    
    public CameraChipBiasgenPanel(CameraChipBiasgen<?> biasgen) {
        this.biasgen = biasgen;
        if(biasgen == null) 
            throw new RuntimeException("null biasgen while trying to construct BiasgenPanel");

        initComponents();
        add(biasgen.getChip().getChipPanel());
        add(biasgen.getChip().getCameraPanel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
