
package uk.ac.imperial.vsbe;

import javax.swing.JPanel;

/**
 * A panel for controlling a PSEyeModelChip and PSEyeCamera
 * This is added to the content panel of BiasgenFrame. 
 * It encapsulates the PSEyeSettingPanel, CameraFramePanel, and PSEyeModelPanel
 *
 * @author  mlk
 */
public class CameraChipBiasgenPanel extends JPanel {
    public CameraChipBiasgen<?> biasgen;
    
    public CameraChipBiasgenPanel(CameraChipBiasgen<?> biasgen) {
        this.biasgen = biasgen;
        if(biasgen == null) 
            throw new RuntimeException("null biasgen while trying to construct BiasgenPanel");

        initComponents();
        //jPanelChip.add(biasgen.getChip().getChipPanel());
        jPanelCamera.add(biasgen.getChip().getCameraPanel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelChip = new javax.swing.JPanel();
        jPanelCamera = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);
        jTabbedPane1.addTab("Chip", jPanelChip);

        jPanelCamera.setLayout(new java.awt.GridBagLayout());
        jTabbedPane1.addTab("Camera", jPanelCamera);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCamera;
    private javax.swing.JPanel jPanelChip;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
