
package uk.ac.imperial.vsbe;

import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.util.Observer;
import java.util.Observable;

/**
 * A panel for controlling a PSEyeModelChip and PSEyeCamera
 * This is added to the content panel of BiasgenFrame. 
 * It encapsulates the PSEyeCameraPanel, CameraFramePanel, and PSEyeModelPanel
 *
 * @author  mlk
 */
public class CameraControlPanel extends JPanel implements Observer {
    GridBagConstraints gbc = new GridBagConstraints();
    Camera camera;
    
    public CameraControlPanel(Camera camera, JPanel settings) {
        this.camera = camera;
        initComponents();
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 0.5;        
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        this.add(settings, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        this.add(new CameraFramePanel(camera), gbc);        
    }   
    
    @Override
    public void update(Observable o, Object arg) {
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
