#ifndef _INCLUDED_DAVISFX3_CONFIG_H_
#define _INCLUDED_DAVISFX3_CONFIG_H_ 1

// Feature configuration
#define PRODUCT_ID 0x1A, 0x84 // Product ID (from Thesycon reserved range)
#define DEVICE_ID  0x00, 0x01

#define STRING_PRODUCT 'D', 0x00, 'A', 0x00, 'V', 0x00, 'I', 0x00, 'S', 0x00, ' ', 0x00, 'F', 0x00, 'X', 0x00, '3', 0x00
#define STRING_PRODUCT_LEN 18

#define USB3_POWER_REQUIREMENT (80)  // 80 x 8mA = 640mA
#define USB2_POWER_REQUIREMENT (250) // 250 x 2mA = 500mA (MAX!)

#define FX3_LOG_LEVEL (LOG_DEBUG)

#define FX3_FIFO_FREQUENCY_DIVIDER (5)

#define FX3_DRIVE_STRENGTH_PPORT (CY_U3P_DS_FULL_STRENGTH)

#define MS_FEATURE_DESCRIPTOR_ENABLED (1)

#define GPIF_32BIT_SUPPORT_ENABLED (1)
#define I2C_SUPPORT_ENABLED (0)
#define SPI_SUPPORT_ENABLED (1)
#define GPIO_SUPPORT_ENABLED (1)

#define GPIO_DEBUG_LED_ENABLED (1)
#define GPIO_DEBUG_LED_NUMBER (51)

#define DEVICE_SPECIFIC_INITIALIZATION (1)
#define DEVICE_SPECIFIC_VENDOR_REQUESTS (1)

#define DMA_USBTOFX3_ONLY (0)
#define DMA_FX3TOUSB_ONLY (1)
#define DMA_USE_MULTICHANNEL (1)

#define FX3_FIFO_DATA_DMA_FX3TOUSB_BURST_LEN (8)
#define FX3_FIFO_DATA_DMA_FX3TOUSB_BUF_COUNT (12)

#define DMA_USBTOFX3_CALLBACK (0)
#define DMA_FX3TOUSB_CALLBACK (0)

#define FX3_SOCKET_0_WATERMARK (7)
#define FX3_SOCKET_1_WATERMARK (7)

#endif /* _INCLUDED_DAVISFX3_CONFIG_H_ */
