package net.sf.jaer2.devices;

import net.sf.jaer2.devices.components.controllers.Controller;
import net.sf.jaer2.devices.components.controllers.FX2;
import net.sf.jaer2.devices.components.misc.memory.EEPROM_I2C;
import net.sf.jaer2.devices.components.misc.memory.Memory;
import net.sf.jaer2.eventio.translators.Translator;

import org.usb4java.Device;

public class FX2Blank extends USBDevice {
	@SuppressWarnings("hiding")
	public static final short VID = 0x04B4;
	@SuppressWarnings("hiding")
	public static final short PID = (short) 0x8613;

	public FX2Blank(final Device usbDevice) {
		super("FX2 Blank", "Blank FX2 device, needs to have firmware loaded onto it.", FX2Blank.VID, FX2Blank.PID,
			USBDevice.DID, usbDevice);

		final Controller fx2 = new FX2(getConfigNode());
		addComponent(fx2);

		fx2.firmwareToRam(true);

		// Size in KB and I2C address.
		final Memory eeprom = new EEPROM_I2C(getConfigNode(), 32, 0x51);
		eeprom.setProgrammer(fx2);
		addComponent(eeprom);

		// Support flashing FX2 firmware.
		fx2.firmwareToFlash(eeprom);
	}

	@Override
	public Class<? extends Translator> getPreferredTranslator() {
		// No events can be generated by the blank devices.
		return null;
	}
}
