
package uk.ac.imperial.pseye;

import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.util.Observer;
import java.util.Observable;

/**
 * A panel for controlling a PSEyeModelChip and PSEyeCamera
 * This is added to the content panel of BiasgenFrame. 
 * It encapsulates the PSEyeSettingPanel, CameraFramePanel, and PSEyeModelPanel
 *
 * @author  mlk
 */
public class PSEyeBiasgenPanel extends JPanel implements Observer {
    public PSEyeBiasgen biasgen;
    GridBagConstraints gbc = new GridBagConstraints();
    
    public PSEyeBiasgenPanel(PSEyeBiasgen biasgen) {
        this.biasgen = biasgen;
        if(biasgen == null) 
            throw new RuntimeException("null biasgen while trying to construct BiasgenPanel");

        initComponents();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        biasgen.getChip().addObserver(this);
        setHardware((PSEyeCamera) biasgen.getChip().getHardwareInterface());
    }   
    
    private void setHardware(PSEyeCamera camera) {
        if (camera != null) {
            gbc.gridx = 0;
            gbc.gridy = 2;
            this.add(camera.getControlPanel(), gbc);        
        }
        
    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (o != null && o == biasgen.getChip() && arg instanceof PSEyeCamera) {
            setHardware((PSEyeCamera) arg);
            revalidate();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
