function [eps,unwrappedTimes]=measureActivity(sampleSizeEvents,filename);
% [eps,t]=measureActivity(sampleSizeEvents[,filename])
% Returns the rate of spike activity in events per second (eps) as a function of
% time (t). sampleSizeEvents specifies the number of events to average over; sampleSizeEvents
% defaults to 1024. If filename is not specified then a dialog is opened.
% A plot is generated by default.
% unwrappedTimes are the event times in seconds, assuming timestamp tick of
% 1e-6 seconds

eventSize=6;

if nargin==0,
    sampleSizeEvents=1024;
end

if nargin<2,
    [filename,pathname,filterindex]=uigetfile('*.dat','Select recorded retina data file');
    if filename==0, return; end
else
    pathname='';
end

f=fopen([pathname,filename],'r');
fseek(f,0,'eof');
numEvents=floor((ftell(f))/eventSize);
fprintf('Total of %d events\n',numEvents);

nSamples=floor(numEvents/sampleSizeEvents);
eps=zeros(1,nSamples);
wrappedTimes=eps;
unwrappedTimes=wrappedTimes;
% unwrap big timestamp wraps
wrapCounter=0;
wrapAdd=(1e-6)*(2^32);

fprintf('reading %d samples of length %d events\n',nSamples,sampleSizeEvents);

fseek(f,0,'bof');
for i=1:nSamples,
    pos=i*sampleSizeEvents*eventSize;
    %     fseek(f,pos,'bof');
    %     addr=int16(fread(f,sampleSizeEvents,'int16',4,'b'));
    fseek(f,2+pos,'bof');
    ts=int32(fread(f,sampleSizeEvents,'int32',2,'b'));
    wrappedTimes(i)=1e-6*double(ts(end));
    if i>1 && wrappedTimes(i)<wrappedTimes(i-1),
        fprintf('w');
        wrapCounter=wrapCounter+1;
    end
    unwrappedTimes(i)=wrappedTimes(i)+wrapCounter*wrapAdd;
    if i>1,
        dt=unwrappedTimes(i)-unwrappedTimes(i-1);
    else
        dt=(1e-6*(double(ts(end)-ts(1))));
    end
    if dt==0,
        warning('zero dt');
        continue;
    end
    eps(i)=sampleSizeEvents/dt;
    fprintf('.');
    if rem(i,90)==0, fprintf('\n'); end;
end
fclose(f);

medianEps=median(eps);
totalTime=unwrappedTimes(end)-unwrappedTimes(1);
meanEps=numEvents/totalTime;


fprintf('\n\nmeanEps=%.2f, medianEps=%.2f\n',meanEps,medianEps);

if 1, %nargout==0,
    figure(1);
%     subplot(211);
    plot(unwrappedTimes,eps)
    xlabel 'time (s)'
    ylabel 'event rate (eps)'
    figure(2);
%     subplot(212);
    plot(1:length(unwrappedTimes),unwrappedTimes,1:length(wrappedTimes),wrappedTimes);
    ylabel 'time (s)'
    xlabel 'sample'
    figure(3);
    hist(eps,100);
    xlabel 'spike rate (Hz)'
    ylabel(['frequency per ' int2str(sampleSizeEvents) ' event packets']);
end

% evalin('

return;

