-- VHDL module instantiation generated by SCUBA Diamond_1.0_Production (529)
-- Module  Version: 5.2
-- Thu Aug 26 09:53:23 2010

-- parameterized module component declaration
component clockgen
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : clockgen
    port map (CLK=>__, RESET=>__, CLKOP=>__, LOCK=>__);
